### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by stuartadamson** [hmrc/income-tax-mtd-changelog#100]
* **I'm submitting a ...**
  - [ ] Bug - API

* **Which API is the issue related to?**
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-reliefs-api/1.0/oas/page#tag/Pensions-Reliefs

* **What is the current behaviour?**
Currently receiving a 500 error code when i use the GOV-TEST-SCENARIO = STATEFUL

* **What is the expected behaviour?**
List all pension reliefs and allow saving new reliefs.

* **Other information** 
The api will return date if I don't use the STATEFUL test header.

**Comment by hmrc-api-team** [comment]
Hi @stuartadamson,

Thank you for the error report. We are currently looking into this and will provide more information as soon as we have any.

MTD API TEAM

**Comment by stuartadamson** [comment]
Perfect. Thank you very much
