### ISSUE TITLE
Amending a periodic update after a BSAS has been triggered

### ISSUE THREAD

**Issue by PhilipHodgson** [hmrc/income-tax-mtd-changelog#11]
If a user amends a periodic update of income and expenditure after a BSAS has been triggered, what happens?

- Is an error raised (but no specific error is listed in the API documentation), or
- is the BSAS invalidated, or
- is the BSAS automatically updated, or
- do the changes not take effect until a new BSAS is triggered?

**Comment by hmrc-api-team** [comment]
The BSAS is calculated at the time of hitting trigger, so if any changes are made after, a new BSAS needs to be triggered.
