### ISSUE TITLE
Can induce a '500 Internal Server Error' when amending a self-employment periodic update

### ISSUE THREAD

**Issue by ac000** [hmrc/income-tax-mtd-changelog#13]
* **I'm submitting a ...**

- [ ] Bug - API

 
* **Which API is the issue related to?**

[Amend a self-employment periodic update](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Amend%20a%20self-employment%20periodic%20update)

* **What is the current behaviour?**

Endpoint returns 500 Internal Server Error when given an invalid businessId.

E.g

```
$ ./mtd-cli sa se-update-period ../test_files/period-2a.json XVIS04154145711 2020-07-06_2020-10-05
```
```JSON
[
    {
        "status_code": 500,
        "status_str": "Internal Server Error",
        "url": "https://test-api.service.hmrc.gov.uk/self-assessment/ni/MZ200944B/self-employments/XVIS04154145711/periods/2020-07-06_2020-10-05",
        "method": "PUT",
        "xid": null,
        "result": {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "An internal server error occurred"
        }
    }
]
```

* **What is the expected behaviour?**

I guess returning a 404 Not Found

Possibly related to #6

**Comment by hmrc-api-team** [comment]
This endpoint (as well as `Get a self-employment periodic update` which was also affected) now returns a 404 for an unknown `selfEmploymentId` in the sandbox.
