### ISSUE TITLE
Reopen production issue with API call to 'Amend a UK Property Income & Expenses Period Summary' 

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/income-tax-mtd-changelog#139]
* **I'm submitting a ...**
  - [ ] Bug - API

* **Which API is the issue related to?**
* [business-details-api](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/business-details-api/2.0)

* **What is the current behaviour?**
* Undocumented error 500 is returned

* **What is the expected behaviour?**
* Success code returned and property business period updated

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
This issue was first reported in Oct 2022 and closed in April 2023 but not fixed.
See Error Log evidence in original issue:
https://github.com/hmrc/income-tax-mtd-changelog/issues/22#issue-1426964809

**Comment by ben-HMRC** [comment]
Apologies for the delay. If you are still experiencing this issue, please report it using the form at https://developer.service.hmrc.gov.uk/developer/support and the Software Developer Support Team will get back to you as soon as possible. We are no longer taking issue reports through GitHub.
