### ISSUE TITLE
Sandbox issue in Individuals Income Received (MTD) API

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/income-tax-mtd-changelog#148]
- [ ] Bug - API

* **Which API is the issue related to?**
 /individuals/income-received/savings/uk-accounts

* **What is the current behaviour?**
ERROR status=500  Internal Server Error

* **What is the expected behaviour?**
SUCCESS status=200

Please find request and response below 

2023-11-22T10:42:01.289 INFO get resource=> /individuals/income-received/savings/uk-accounts/HM201123A headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=2560&height=1440&scaling-factor=1.3499999046325684&colour-depth=24',
  'gov-client-timezone': 'UTC+00:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': '',
  'gov-client-window-size': 'width=1650&height=1264',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '3b5af9a0-32a3-11ee-ab95-37cccb9880b4',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'gov-client-local-ips': '0f0379c2-7d87-41fd-a8e0-9554156b84b0.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2023-11-22T10:41:58.616Z',
  'gov-client-local-ips-timestamp': '2023-11-22T10:41:58.616Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 50796,
  'gov-client-user-ids': 'SE_reportsUser=HM201123A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.1.0+json',
  Authorization: 'Bearer 7772d880393a53552e56f3b07e56c056'
}
2023-11-22T10:42:02.354 INFO get status=500

Same API call was correctly processed recently, please see log below

2023-11-22T10:33:24.322 INFO get  resource=> /individuals/income-received/savings/uk-accounts/HM201123A headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=1800&height=900&scaling-factor=1.0000000298023224&colour-depth=24',
  'gov-client-timezone': 'UTC+00:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': 'PDF%20Viewer,Chrome%20PDF%20Viewer,Chromium%20PDF%20Viewer,Microsoft%20Edge%20PDF%20Viewer,WebKit%20built-in%20PDF',
  'gov-client-window-size': 'width=1800&height=900',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '8a45d5f0-8922-11ee-ad30-11ba80ea5fa3',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
  'gov-client-local-ips': '6b0bb632-5b93-4a8c-bad7-aed32b251151.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2023-11-22T10:33:21.802Z',
  'gov-client-local-ips-timestamp': '2023-11-22T10:33:21.802Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 50657,
  'gov-client-user-ids': 'SE_reportsUser=HM201123A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.1.0+json',
  Authorization: 'Bearer a739d411e8b62d802538c66c9a40042d'
}
2023-11-22T10:33:24.513 INFO get  status=200

**Comment by abigail-houston-hmrc** [comment]
We believe this is now fixed, please contact SDST if you are still experiencing issues

**Comment by alexei-serjantov** [comment]
The issue is Resolved
