### ISSUE TITLE
Unable to create uk-property update period in sandbox

### ISSUE THREAD

**Issue by chrisyoulden** [hmrc/income-tax-mtd-changelog#15]
The following steps are taken:

create-test-user/individuals to create a test user and then the user is signed in and access granted

self-assessment/ni/{}/uk-properties is used to create a test uk-property

individuals/business/details/{}/list is used to obtain a business id for the uk-property business
obligations/details/{}/income-and-expenditure is used to obtain obligations for the business id

self-assessment/ni/{}/uk-properties/other/periods is used to submit the first obligation period's data:
"from": "2018-04-06", "to": "2018-07-05"
which results in:
{"code":"BUSINESS_ERROR","message":"Business validation error","errors":[{"code":"MISALIGNED_PERIOD","message":"Period is not within the accounting period.","path":""}]}

I understand the obligations are hard-coded data and so the year 2018-2019 obligations are always returned. And I have read the other issues relating to this regarding self-employment. The difference is that with self-employment the accounting period start date can be specified when creating a self-employment business and then the advice was to submit the period data for that start date.

However, I need to test the uk-property business functionality and no accounting period can be specified for the creation of the test property. I cannot see how to determine which accounting period is in use for the test property or determine which period dates should be submitted. I do not wish to create a self-employment business and need to work only with the uk-property business.

Please let me know if I am doing something wrong or there is an API call I have missed or a Gov-Test-Scenario that can be used.

**Comment by ac000** [comment]
Seeing as it seems that the end goal is to remove the self-assessment API and have the whole thing be stateless, I would concentrate on figuring out what date periods it's looking for. 

Have you tried

```JSON
"from": "2020-04-06",                                                       
"to": "2020-07-05", 
```

for the date period?

**Comment by chrisyoulden** [comment]
Seems the period submission for uk-property needs to be 2017-2018. However other API's do not allow periods so early, such as BSAS which has an earliest allowable tax year of 2019-20.

So a workaround is to read the obligations from the new api - and if in the sandbox then adjust them from 2018-2019 to 2020-2021 instead. This more recent year should work with the newer api. Then when submitting a uk-property period and in the sandbox adjust the year to 2017-2018.

**Comment by ac000** [comment]
I've had to play similar games with the businessId for self-employment businesses.

Things should hopefully improve next year. https://developer.service.hmrc.gov.uk/roadmaps/mtd-itsa-vendors-roadmap/ check under 'Production by End of April 2022'.

**Comment by hmrc-api-team** [comment]
Closing this issue for now. If it's still something that we need to investigate, please open as a new issue - thanks.
