### ISSUE TITLE
Live Production Issue MTD Pilot

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/income-tax-mtd-changelog#150]
**Note: Please read before raising an issue**. 

* **I'm submitting a ...**
  - [ ] Bug - API

* **Which API is the issue related to?**
 List Property Income and Expenses Period Summaries

* **What is the current behaviour?**
* Error 500 is returned

* **What is the expected behaviour?**
* Success code 200 with a list of submissions

API trace log: 
2023-11-29T09:37:14.490 INFO get resource=> /individuals/business/property/PB966848A/XJIS00000001249/period/2023-24 headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=2560&height=1440&scaling-factor=1.125&colour-depth=24',
  'gov-client-timezone': 'UTC+00:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': '',
  'gov-client-window-size': 'width=2668&height=1611',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '3b5af9a0-32a3-11ee-ab95-37cccb9880b4',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'gov-client-local-ips': '32b2fe9b-11f7-47a5-90ee-6a7e4a05caa9.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2023-11-29T09:36:50.504Z',
  'gov-client-local-ips-timestamp': '2023-11-29T09:36:50.504Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 65474,
  'gov-client-user-ids': 'SE_reportsUser=PB966848A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.2.0+json',
  Authorization: 'Bearer f350b68944625f5d20cdbe74dc905188'
}
2023-11-29T09:37:16.951 INFO get status=500

**Comment by ben-HMRC** [comment]
If you are still experiencing this issue, please report it using the form at https://developer.service.hmrc.gov.uk/developer/support and the Software Developer Support Team will get back to you as soon as possible.
