### ISSUE TITLE
Http Error 500 (Internal Server Error) - Business Details MTD api

### ISSUE THREAD

**Issue by dvdfmiller** [hmrc/income-tax-mtd-changelog#17]
**Error
------**
In the sandbox I issue an http Get for  a list of businesses using  Business Details MTD api with:
`https://test-api.service.hmrc.gov.uk/individuals/business/details/<nino>/list`
&
`Header Gov-Test-Scenario  value = "N/A-DEFAULT"`

I get an error:
`Http Error 500 (Internal Server Error)`

I expected to get back a Self Employment business.

**Work Around
-----------------**
I found that if I issue the http Get without any Gov-Test-Scenario Header then I successfully get back a Self Employment business.
nb other Gov-Test-Scenario Header values work correctly.

Hope this helps.
best regards
David

**Comment by ac000** [comment]
I don't think that you're actually supposed to use "N/A-DEFAULT" as a header value. I think in the documentation it's just showing what the behaviour is if you _don't_ specify any Gov-Test-Scenario header.

At the same time, it should probably handle unknown Gov-Test-Scenario values better...

**Comment by dvdfmiller** [comment]
Ah I see - I understand the documentation now.

thanks
David
