### ISSUE TITLE
Issue with getting ITSA - annual summary

### ISSUE THREAD

**Issue by bartoszpietras** [hmrc/income-tax-mtd-changelog#18]
Can I get advice on problem with getting annual summary data.

First what I’m doing is:
1)	Create user – works ok
2)	Create selfemploymentbusiness - https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Add%20a%20self-employment%20business%20[test%20support] – works ok
3)	Pushing periodic update (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Create%20a%20self-employment%20periodic%20update) within the period retrieved by creating the business above – works ok
4)	Trigger calculation (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/2.0#Trigger%20a%20Self%20Assessment%20Tax%20Calculation) – works ok
5)	Check the data on HMRC (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Get%20a%20self-employment%20periodic%20update) we see the update there – works ok
6)	Retrieve tax estimate (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/2.0#Retrieve%20Self%20Assessment%20Tax%20Calculation%20End%20Of%20Year%20Estimate) – works ok
7)	Try to get (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Get%20a%20self-employment%20annual%20summary) – **does not work … we get 404**.

We use here selfemploymentid of the business generated in (2) tax period from this business and nino from generated user in (1)
(Real call GET /self-assessment/ni/PG504241A/self-employments/XUIS38003962064/2018-19)

Can we get a help on that please.
Thanks,

**Comment by bartoszpietras** [comment]
Thanks for the answer,
So do I get it wrong that that the data on annual summary should be populated by posting periodic updates and triggering calculation? 
Annual summary data needs to be posted from product?
Thanks,

**Comment by kumarparekh** [comment]
Hi All,
Were you guys about to resolve this?
Just checking in to see because we are also facing some issues with this.
WE tried to do steps 1 to 7 as per above.

Steps 1-6 work but there is no reflection of that informatin in the Step 7.

Are Periodic Updates and Annual summary related? or do we need to trigger that through some other calculation API?

Thanks.

**Comment by abigail-houston-hmrc** [comment]
This endpoint has now been deprecated, and will be retired shortly. Please use the Self Employment Business (MTD) API instead. Regarding the relationship between periodic and annual summaries, please can you contact [SDST](https://developer.service.hmrc.gov.uk/developer/support) directly
