### ISSUE TITLE
Getting adjustable summary

### ISSUE THREAD

**Issue by bartoszpietras** [hmrc/income-tax-mtd-changelog#19]
Hi,

There is another issue with ITSA API.
When triggering BSAS https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-bsas-api/2.0#Trigger%20a%20Business%20Source%20Adjustable%20Summary%20(BSAS) the API returns the following response:
{
    "id": "717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4",
    "links": [
        {
            "href": "/individuals/self-assessment/adjustable-summary/ZX559584B/self-employment/717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4",
            "method": "GET",
            "rel": "self"
        }
    ]
}

But when I try to get that value “/individuals/self-assessment/adjustable-summary/ZX559584B/self-employment/717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4/” I get
{
    "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "Matching resource not found"
}

What I am doing wrong?
Thanks,

**Comment by zharenov** [comment]
Hi, I have the same issue. Just sent a question to support.

**Comment by ac000** [comment]
You can fudge it by setting a _Gov-Test-Scenario_ header such as

    Gov-Test-Scenario: SELF_EMPLOYMENT_ADJUSTED

The underlying issue may be due to the new stateless stuff, it's been a source of such issues in the past. In this case it may be that the bsasId expected by _/individuals/self-assessment/adjustable-summary/NINO/self-employment/BSASID_ is not the one returned from _/individuals/self-assessment/adjustable-summary/NINO/trigger_

**Comment by hmrc-api-team** [comment]
Hi,

If you refer to the documentation for Retrieve a Self Employment BSAS https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-bsas-api/2.0#Retrieve%20a%20Self you will see under the Test Data heading that the default response for this endpoint is NOT_FOUND. Please use one of the Gov-Test-Scenarios to simulate the retrieval of data. 

Hope this is helpful, let us know if you require any further information.

**Comment by zharenov** [comment]
Hi, thank you, understood

**Comment by kumarparekh** [comment]
Hi All,
Were you guys about to resolve this?
Just checking in to see because we are also facing some issues with this.

Thanks.

**Comment by ev-geniy-tlt** [comment]
Hi @kumarparekh 
If I remember correctly - we use workaround by adding the header: Gov-Test-Scenario: SELF_EMPLOYMENT_ADJUSTED
