### ISSUE TITLE
Internal server error while getting list of calculations

### ISSUE THREAD

**Issue by bartoszpietras** [hmrc/income-tax-mtd-changelog#20]
Hi,

I have the account and self employment set up on sandbox. I'm able to push periodic updates 
However when I try to trigger calculations or get a list of calculations 
/individuals/calculations/{nino}/self-assessment (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/2.0#List%20Self%20Assessment%20Tax%20Calculations) I am getting this response
{
    "code": "INTERNAL_SERVER_ERROR",
    "message": "An internal server error occurred"
}

The same happens for intent to crystalize /individuals/calculations/crystallisation/{nino}/{taxYear}/intent-to-crystallise (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/2.0#Intent%20to%20Crystallise)
All headers are sent accordingly to documentation.
Please help.
Thanks,
Bart.

**Comment by RachGibbons** [comment]
Database has been reset. Can you please try hitting these endpoints again.

**Comment by bartoszpietras** [comment]
Works correctly now.
