### ISSUE TITLE
Create Marriage Allowance

### ISSUE THREAD

**Issue by stuartadamson** [hmrc/income-tax-mtd-changelog#21]
**I'm submitting a Support request/Bug**
**Which API is the issue related to?**
Individuals Disclosures (MTD) API
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individuals-disclosures-api/1.0#Create%20Marriage%20Allowance

* **What is the current behaviour?**
[http_code] => 400
[code] => INVALID_REQUEST
[message] => Invalid request
* **What is the expected behaviour?**
Depending on the Gov-Test-Scenario either Sucessful response (201) or one of the error messages listed in the Error scenarios.

* **Other information** 
Trying to submit test data (example data from the Request section of the page but when I post it i am getting the 400 - INVALID_REQUEST. Was expected to see HTTP status 201. I added the Gov-Test-Scenario and tried "DEFAULT", "DECEASED_RECIPIENT", "CLAIM_ALREADY_EXISTS" and "INVALID_REQUEST" but i get the same response.
Am i doing something wrong?

**Comment by hmrc-api-team** [comment]
I will suggest you look at the json body you are sending to make sure you are not sending an empty body or incomplete json as everything is working well at this end

**Comment by stuartadamson** [comment]
Thank you for your response and really sorry for wating your time. You where correct.  Me being dense.
