### ISSUE TITLE
Production Issue #2

### ISSUE THREAD

**Issue by alexei-serjantov** [hmrc/income-tax-mtd-changelog#23]
* **I'm submitting a ...**
  - [ ] Bug - API

* **What is the current behaviour?**
Server retuerned undocumented error code 500

* **What is the expected behaviour?**
Not found Error 404

* **Other information** Called API log 

2022-11-09T09:30:35.964 INFO get 0 resource=> /self-assessment/ni/PB966848A/self-employments/XXIS00000001248/2022-23 headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=3072&height=1728&scaling-factor=1.25&colour-depth=24',
  'gov-client-timezone': 'UTC+00:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': '',
  'gov-client-window-size': 'width=1544&height=1508',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '44435e50-c47b-11ec-91b1-ef719a7cae09',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
  'gov-client-local-ips': '6a79ae66-b302-4f7f-8ccb-c6e34f92c872.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2022-11-09T09:30:25.426Z',
  'gov-client-local-ips-timestamp': '2022-11-09T09:30:25.426Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 50512,
  'gov-client-user-ids': 'SE_reportsUser=PB966848A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.2.0+json',
  Authorization: 'Bearer 5598ff0eb65b0546f6ae0e767080603e'
}
2022-11-09T09:30:36.857 INFO get 0 status=500
2022-11-09T09:30:36.857 ERROR GET 500 {"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}

Correct behaviour log in October

2022-10-17T09:43:50.301 INFO get 0 status=200
2022-10-17T09:43:50.304 INFO get 1 resource=> /self-assessment/ni/PB966848A/self-employments/XXIS00000001248/2022-23 headers=> {
  'gov-vendor-license-ids': '',
  'gov-client-browser-do-not-track': 'false',
  'gov-client-screens': 'width=3072&height=1728&scaling-factor=1.25&colour-depth=24',
  'gov-client-timezone': 'UTC+01:00',
  'gov-client-connection-method': 'WEB_APP_VIA_SERVER',
  'gov-client-browser-plugins': '',
  'gov-client-window-size': 'width=1686&height=1278',
  'gov-vendor-version': 'SE_reportsServer=2.0&SE_reportsClient=2.0',
  'gov-client-multi-factor': '',
  'gov-client-device-id': '44435e50-c47b-11ec-91b1-ef719a7cae09',
  'gov-client-browser-js-user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
  'gov-client-local-ips': '15d8a818-e5ad-4da0-a72c-c7b4fb8a7e1f.local',
  'gov-vendor-public-ip': '81.150.62.73',
  'gov-client-public-ip': '81.150.62.73',
  'gov-client-public-ip-timestamp': '2022-10-17T08:43:37.194Z',
  'gov-client-local-ips-timestamp': '2022-10-17T08:43:37.194Z',
  'gov-vendor-product-name': 'SE_reports',
  'gov-client-public-port': 43014,
  'gov-client-user-ids': 'SE_reportsUser=PB966848A',
  'gov-vendor-forwarded': 'by=81.150.62.73&for=81.150.62.73',
  Accept: 'application/vnd.hmrc.2.0+json',
  Authorization: 'Bearer a3fca0d33d45385ef73d031406edbf39'
}
2022-10-17T09:43:52.334 INFO get 1 status=404

**Comment by abigail-houston-hmrc** [comment]
We have deprecated this endpoint, and it will be retired in a few months. The replacement endpoint is in the Self Employment Business  (MTD) API
