### ISSUE TITLE
v2 Mapping  document for SA103F doesn't display in a 'pretty' format

### ISSUE THREAD

**Issue by leslie-mcquigg** [hmrc/income-tax-mtd-changelog#248]
The v2 Mapping document for the SA103F contains an error:

[income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/tree/main)/[mapping](https://github.com/hmrc/income-tax-mtd-changelog/tree/main/mapping)/[csv](https://github.com/hmrc/income-tax-mtd-changelog/tree/main/mapping/csv)
/sa103f_mapping_v2.csv

**Comment by ben-HMRC** [comment]
Thanks for reporting this. The problem was some extra whitespace at the end of a line that was confusing Github's CVS renderer. We have released a new version of the file which corrects the issue.
