### ISSUE TITLE
Life cycle of a Business Source Adjustable Summary (BSAS)

### ISSUE THREAD

**Issue by PhilipHodgson** [hmrc/income-tax-mtd-changelog#8]
For the same business and accounting period, do the adjustments in a BSAS cease to have effect:

   when a new BSAS is triggered?

   or when a new BSAS is triggered and adjustments posted against it?

Or am I missing the point and the adjustments are cumulative, and never cease to have effect?

**Comment by hmrc-api-team** [comment]
The adjustments will no longer have effect when a new BSAS is triggered (any old adjustments would still 'exist', but they would be against a superseded BSAS calculation so effectively just ignored).
