### ISSUE TITLE
Non-FHL UK property business and rarRentReceived

### ISSUE THREAD

**Issue by PhilipHodgson** [hmrc/income-tax-mtd-changelog#9]
The _Create a non-FHL UK property update period_ endpoint includes an item under income of _rarRentReceived_, but if you attempt to adjust this in the corresponding BSAS you get a non-matching body error (in the sandbox).

Is that by design or is it a fault?

I have tested adjusting every item of income and expenses for every type of business and this is the only one that causes an error. A few others are omitted from the documentation for the adjust endpoints, but they do not cause an error.

Two items also had a slight name change. _costsOfServices_ became _costOfServices_ and _premiumOfLeaseGrant_ became _premiumsOfLeaseGrant_ (note the additional s), but after adjusting for that all was ok.

**Comment by hmrc-api-team** [comment]
Unfortunately, although `rarRentReceived` can be retrieved, it cannot currently be adjusted. The fields that can be adjusted are described in the endpoint documentation.
